### ISSUE TITLE
Fail to build with Qt5.5

### ISSUE THREAD

**Issue by bigeagle** [zealdocs/zeal#376]
Hi there,
It seems zeal cannot build with recently released Qt 5.5
```
main.cpp: In function ‘int main(int, char**)’:
main.cpp:193:29: error: variable ‘QDataStream out’ has initializer but incomplete type
             QDataStream out(socket.data());
                             ^
```
Please consider fixing this. Thank you for all your work!

Cheers,
Justin

**Comment by dmarcoux** [comment]
I also have this issue.
