### PR TITLE
Fix #376: Add a missing include

### LINKED ISSUE #376: Fail to build with Qt5.5
Hi there,
It seems zeal cannot build with recently released Qt 5.5
```
main.cpp: In function ‘int main(int, char**)’:
main.cpp:193:29: error: variable ‘QDataStream out’ has initializer but incomplete type
             QDataStream out(socket.data());
                             ^
```
Please consider fixing this. Thank you for all your work!

Cheers,
Justin

### PR DESCRIPTION
**Pull request by Xinkai**
Fix building with Qt 5.5

### CODE REVIEW

**Comment by jaypei** [comment]
+1

**Comment by trollixx** [comment]
Thanks, I fixed the problem in 0.1 branch (79fe23b8baca4179ea18e673225ee104a2ffded5), and then it's been merged in master.
