### ISSUE TITLE
Toml++ only ships toml.h (not toml.hpp) in versions older than 3.4

### ISSUE THREAD

**Issue by neoh4x0r** [zealdocs/zeal#1958]
I'm using Debian 12 (Bookworm) with libtomlplusplus-dev (v3.3) and the build systems fails to include toml.hpp because the development library only ships toml.h and it is looking for toml.hpp

However, in Debian 13 (Trixe) and unstable, with version 3.4, they ship both header files.

It seems like it would be better to look for toml.h and possibly  have a compatibility symlink in the contrib directory that links to toml.hpp for consistency.

```
$ apt-cache policy libtomlplusplus-dev
libtomlplusplus-dev:
  Installed: 3.3.0+ds-1
  Candidate: 3.3.0+ds-1
  Version table:
 *** 3.3.0+ds-1 1090
       1090 https://deb.debian.org/debian bookworm/main amd64 Packages

$ ls /usr/include/toml++
.  ..  impl  toml.h

ERROR:
/build/zeal/src/libs/core/session.cpp:15:10: fatal error: toml++/toml.hpp: No such file or directory
   15 | #include <toml++/toml.hpp>
```

**Comment by trollixx** [comment]
I'll check in a bit. It sounds like Bookworm is just too old, older than Ubuntu 24.04 LTS.

My general policy is to target the latest Ubuntu LTS once the `.1` point release is out. E.g. 26.04.1 should be out on August 27th. The 0.10.x Zeal version will have updated dependency requirements, specifically Qt 6.10.2+.

**Comment by neoh4x0r** [comment]
> My general policy is to target the latest Ubuntu LTS once the `.1` point release is out. E.g. 26.04.1 should be out on August 27th. The 0.10.x Zeal version will have updated dependency requirements, specifically Qt 6.10.2+.

That might cause some issues for Debian stable (Trixie) users unless, or until, QT 6.10 is backported from Testing - assuming it's a hard requirement and things won't work on 6.8 or earlier.

**Comment by trollixx** [comment]
I reviewed the dependencies, technically, Bookworm is supposed to be supported by the 0.9 branch. The linked PR should fix the build system.
